export const pageHome = "/"
export const pageTopPosts = "/top-posts"
export const pageWsbChatbot = "/wsb-chatbot"
export const pageTrading = "/trading"
export const pageTickerDetail = "/ticker/:ticker"
